spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/talktown_userdb
        username: talktown
        password: talktown123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    application:
        name: user-service
    cloud:
        config:
            enabled: true
            uri: http://localhost:8888
            
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html

keycloak:
    realm: talktown-realm
    auth-server-url: http://localhost:8080
    resource: user-service
    public-client: true
    bearer-only: true